---

- name: Admin_SG_brazil
  ec2_group:
    name: Admin_SG_brazil
    description: "A Security group of San Paulo region"

    region: "{{ ec2_region }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp            
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 5601
        to_port: 5601
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 9200
        to_port: 9200
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8081
        to_port: 8081
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: Create EC-2 instance
  ec2:
    region: "{{ ec2_region }}"
    group_id: "{{ basic_firewall.group_id }}"   
    instance_type: t2.micro
    image: "{{ ami_id }}"
    key_name: "{{ key_name }}"
    instance_tags:
      Name: my_instance
    exact_count: 1
    count_tag:
      Name: my_instance
    wait: true
  register: ec2host #Var_for_store_result_of_task

- name: add_host
  add_host:
   name: host_ip
   ansible_ssh_host: "{{ ec2host.tagged_instances[0].public_ip }}"

- name: Wait for ssh #Wait_for_instance_to_start_ssh_service
  wait_for:
    port: 22
    delay: 20
    host: "{{ ec2host.tagged_instances[0].public_ip }}"
